name: CI

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  tests:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        python-version:
        - '3.10'
        - '3.11'
        - '3.12'
        - '3.13'
        - '3.14'

    steps:
    - uses: actions/checkout@v5

    - name: Install uv and set the Python version
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ matrix.python-version }}
        enable-cache: true

    - name: Install the project
      run: |
        uv sync --locked --all-extras --dev
        uv tool install tox --with tox-uv

    - name: Run tox targets for ${{ matrix.python-version }}
      run: tox run -f py$(echo ${{ matrix.python-version }} | tr -d . | cut -f 1 -d '-')

#    - name: Run extra tox targets
#      if: ${{ matrix.python-version == '3.13' }}
#      run: |
#        tox -e base,dist,docs

#    - name: Upload coverage
#      uses: codecov/codecov-action@v5
#      with:
#        env_vars: TOXENV,DJANGO
